[versions]
kotlin = "2.3.21"
paperweight = "2.0.0-beta.22"
minecraft-server = "4.0.2"
shadow = "9.4.1"
spigot = "26.1.2-R0.1-SNAPSHOT"
sqlite-jdbc = "3.53.0.0"
mysql-connector-j = "9.7.0"
mockito = "5.23.0"
maven-publish = "0.37.0"
dokka = "2.2.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
minecraft-server = { id = "dev.s7a.gradle.minecraft.server", version.ref = "minecraft-server" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector-j" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
